server.port=8080
spring.mongodb.uri=${MONGO_URI}
server.address=0.0.0.0
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.error.include-message=always
